config/routes.rb
Rails.application.routes.draw do
  
  root 'boards#index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users

  resources :boards

  resources :lists

  resources :cards, except: [:index]

  resources :comments, except: [:index]
  
  get 'labels' => 'labels#new'
  post 'labels' => 'labels#create'
  delete 'labels' => 'labels#delete'

end

app/models/board.rb
class Board < ActiveRecord::Base
  validates :name, presence: true

  belongs_to :user
  has_many :lists
end

app/models/card.rb
class Card < ActiveRecord::Base
  validates :title, presence: true

  belongs_to :user
  belongs_to :list
  has_many :labels
  has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :body, presence: true

  belongs_to :user
  belongs_to :card
end

app/models/label.rb
class Label < ActiveRecord::Base
  validates :color, presence: true

  belongs_to :card
end

app/models/list.rb
class List < ActiveRecord::Base
  validates :title, presence: true

  belongs_to :user
  belongs_to :board
  has_many :cards
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :name, :username, :email, :password, presence: true
  validates :username, :email, uniqueness: true

  has_many :boards
  has_many :lists
  has_many :cards
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController

	include SessionsHelper

	def index
		@boards = Board.all
		@board = Board.new
	end

	def show
		@board = Board.find_by(id: params[:id])
		@new_list = List.new
		@card = Card.find_by(id: params[:id])
		@new_card = Card.new
	end

	def new
		@board = Board.new
	end

	def edit
		@board = Board.find_by(id: params[:id])
	end

	def create
		@board = current_user.boards.build(board_params)
		if @board.save
			redirect_to @board
		else
			render 'new'
		end
	end

	def update
		@board = Board.find_by(id: params[:id])
    	if @board.update(board_params)
      		redirect_to @board
    	else
      		render 'edit'
    	end
	end

	def destroy
		@board = Board.find_by(id: params[:id])
		@board.destroy
		redirect_to boards_path
	end

private

def board_params
  params.require(:board).permit(:name)
end

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  include SessionsHelper
	
	def show
		@card = Card.find_by(id: params[:id])
	end

	def new
		@card = Card.new
	end

	def edit
		@card = Card.find_by(id: params[:id])
	end

	def create
    @list = List.find_by(id: params[:card][:list_id])
		@card = current_user.cards.build(card_params)
		if @card.save
			redirect_to @list.board
		else
			render 'new'
		end
	end

	def update
		@card = Card.find_by(id: params[:id])
		if @card.update(card_params)
			redirect_to @card.list
		else
			render 'edit'
		end
	end

	def destroy
		@card = Card.find_by(id: params[:id])
		@card.destroy
		redirect_to @card.list 
	end

private

	def card_params
  		params.require(:card).permit(:title, :description, :list_id)
	end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def new
		@comment = Comment.new
	end

	def edit
		@comment = Comment.find_by(id: params[:id])
	end

	def create
		@card = Card.find_by(id: params[:id])
		@comment = @card.comments.new(comment_params)
		if @comment.save
			redirect_to @card
		else
			render 'new'
		end
	end

	def update
		@card = Card.find_by(id: params[:id])
		@comment = @card.comments.find_by(id: params[:id])
		if @comment.update(comment_params)
			redirect_to @card
		else
			render 'edit'
		end
	end

	def destroy
		@comment = Comment.find_by(id: params[:id])
		@comment.destroy
		redirect_to comments_path
	end

private

def comment_params
  params.require(:comment).permit(:body)
end

end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
	def new
		@label = Label.new
	end

	def create
		@card = Card.find_by(id: params[:id])
		@label = @card.labels.new(label_params)
		if @label.save
			redirect_to @card
		else
			render 'new'
		end
	end

	def destroy
		@label = Label.find_by(id: params[:id])
		@label.destroy
		redirect_to labels_path
	end

private

	def label_params
		params.require(:label).permit(:color)
	end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  include SessionsHelper

  def new
    @list = List.new
  end

  def edit
    @list = List.find_by(id: params[:id])
  end

  def create
    @board = Board.find_by(id: params[:list][:board_id])
    @list = current_user.lists.build(list_params)
    if @list.save
      redirect_to @board
    else
      render 'new'
    end
  end

  def update
    @board = Board.find_by(id: params[:id])
    @list = @board.lists.find_by(id: params[:id])
    if @list.update(list_params)
      redirect_to @board
    else
      render 'edit'
    end
  end

  def destroy
    @board = Board.find_by(id: params[:id])
    @list = @board.lists.find_by(id: params[:id])
    @list.destroy
    redirect_to @board
  end

private

def list_params
  params.require(:list).permit(:title,:board_id)
end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      session[:id] = @user.id
      redirect_to root_path
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    session.delete(:id)
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find_by(id: params[:id])
	end

	def new
		@user = User.new
	end

	def edit
		@user = User.find_by(id: params[:id])
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to @user
		else
			render 'new'
		end
	end

	def update
		@user = User.find_by(id: params[:id])
		if @user.update(user_params)
			redirect_to @user
		else
			render 'edit'
		end
	end

	def destroy
		@user = User.find_by(id: params[:id])
		@user.destroy
		redirect_to users_path
	end

private

def user_params
  params.require(:user).permit(:name, :username, :email, :password)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:id] = user.id
  end

  def logged_in?
    !current_user.nil?
  end

  def current_user
    @user ||= User.find_by(id: session[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boards/edit.html.erb
<h1>Hello, board edit!</h1>

app/views/boards/index.html.erb
<section class="boards-container">
<h1>Trello-On-Rails</h1>

<% if logged_in? %>

<h2>My Boards</h2>
  <% @boards.each do |board| %>
    <div class="board-index-link"><a href="boards/<%= board.id %>"><%= board.name %></a></div>
  <% end %>

   <article class="new-board-form">
    <h3>Create a new board</h3>
    <%= form_for @board do |f| %>
      <%= f.label :name %>
        <%= f.text_field :name, class: "new-board-name" %><br>
        <%= f.submit "Create", class: "create-board" %>
    <% end %>
    </article>

<% else %>
  <h3 class="sign-in-notice">Log in or register to see your boards!</h3>
</section>
<% end %>

app/views/boards/new.html.erb
<h1>Hello, new board!</h1>

app/views/boards/show.html.erb
<%= link_to 'Go Back', boards_path %>

<div class="board" class="container">
<h1 class="board-name"><%= @board.name %></h1>

<div class="row">
  <ul class="list-container">
    <% @board.lists.each do |list| %>
     <li class="list col-md-3">
        <h3 class="list-title"><%= list.title %></h3>
        <% list.cards.each do |card| %>
          <div class="card-title" draggable="true"><a href="/cards/<%= card.id %>"><%= card.title %></a></div>
        <% end %> 

        <div class="form-group">
          <div>
            <%= form_for(@new_card) do |f| %>
              <p><%= f.text_field :title, placeholder: "title", class: "form-control" %></p>
              <p><%= f.text_field :description, placeholder: "description", class: "form-control" %></p>
              <%= f.hidden_field :list_id, value: list.id %>
              <%= f.submit "Add a card", class: "btn btn-primary" %>
            <% end %>
          </div>
        </div>
      <% end %>
    </li>

    <li>
      <div class="form-group">
        <div class="col-md-12">
          <%= form_for(@new_list) do |f| %>
            <p><%= f.text_field :title, placeholder: "title", class: "form-control" %></p>
            <%= f.hidden_field :board_id, value: @board.id %>
            <%= f.submit "Create a list", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </li>

  </ul>
</div>

</div>

app/views/cards/edit.html.erb
<h1>Hello card edit!</h1>

<%= form_for [@card] do |f| %>
 
  <div>
    <%= f.label :title %>:<br>
    <%= f.text_field :title, 
                     class: "form-control" %>
  </div>
 
  <div>
    <%= f.label :body %>:<br>
    <%= f.text_area :description, 
                    class: "form-control",
                    rows: "15",
                    id: "comment" %>
  </div>
 
  <div>
    <%= f.submit class: "btn btn-primary" %>
  </div>
 
<% end %>

app/views/cards/new.html.erb
 <div>
  <%= form_for(@new_card) do |f| %>
    <p><%= f.text_field :title, placeholder: "title", class: "form-control" %></p>
    <p><%= f.text_field :description, placeholder: "description", class: "form-control" %></p>
      <%= f.hidden_field :list_id, value: @new_card.list.id %>
      <%= f.submit "Add a card", class: "btn btn-primary" %>
    <% end %>
 </div>

app/views/cards/show.html.erb
<h1>Hello card!</h1>

<%= link_to 'delete card', card_path(@card),
            method: :delete,
            data: { confirm: 'Delete this card?'} %>

<%= link_to 'Edit',
      edit_card_path(@card) %>

app/views/users/_errors.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Register:</h1>


<div class="form-group">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <p><%= f.text_field :name, placeholder: "name", class: "form-control" %></p>
      <p><%= f.text_field :username, placeholder: "username", class: "form-control" %></p>
      <p><%= f.email_field :email, placeholder: "example@email.com", class: "form-control"  %></p>
      <p><%= f.password_field :password, placeholder: "password", class: "form-control" %></p>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1>Hello, user!</h1>